upgrading_to_fusion:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"

      user: "{{ env_var('USER') }}"
      password: "{{ env_var('PASSWORD') }}" # enter password you used to signup for Snowflake demo account here
      role: ACCOUNTADMIN
      
      database: snowflake_learning_db
      warehouse: compute_wh
      schema: dbt_treamcelhone
    fusion_dev:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"

      user: "{{ env_var('USER') }}"
      password: "{{ env_var('PASSWORD') }}" # enter password you used to signup for Snowflake demo account here
      role: ACCOUNTADMIN
      
      database: snowflake_learning_db
      warehouse: compute_wh
      schema: fusion_dev
